### ISSUE TITLE
Failed to Create Report - MailboxPermissionsReport

### ISSUE THREAD

**Issue by MilesAnderson11** [ruudmens/LazyAdmin#10]
It seems as if some of the functionality is broken within the script. 

Getting "Failed to create report" with no sign of where the error occurs. This only happens when running switches such as csv files, manually entering names. Does not happen when running the script without any switches. 

It will create the CSV but not populate with information. 

Does not matter where the csv output is going, whether or not the switch for the csv output is used etc.

The screenshot used shows close exchange online connection No but this problem happens regardless and the last success (with the all users no switches was run after a no)
![Screenshot 2022-07-11 125034](https://user-images.githubusercontent.com/106215551/178179906-58d446f5-d79a-4d21-8128-2088c9cdf2d3.png)

Also an enhancement request is it possible to create the following switch?

A way to have each line email the respective mailbox owner of who has permissions? But only be for that specific user?

**Comment by ruudmens** [comment]
Try the latest version, CSV switch is updated.
