### ISSUE TITLE
Error "operator is reserved for future use."

### ISSUE THREAD

**Issue by maeck** [ruudmens/LazyAdmin#14]
I get these error, while using the paramter "./MailboxPermissionReport.ps1 -adminUPN marcel.xyz@domain.de -sharedMailboxes only" with Visual Studio Code at MacOS.

ParserError: /Users/mec/pwsh/MailboxPermissionReport.ps1:206:209
Line |
 206 |  … k Button--medium Button d-lg-none color-fg-inherit p-1">    <span cla …
     |                                                                ~
     | The '<' operator is reserved for future use.

**Comment by ruudmens** [comment]
There isn't a line of code in the script with `Button--medium Button d-lg-none color-fg-inherit p-1"> <span class`
It looks like a piece of HTML code, but I have no idea where it's coming from.

What happens when you run the script with PowerShell instead of Visual Studio Code?

**Comment by maeck** [comment]
I'm sorry. It was an error during copy & pasting the script ...
