### ISSUE TITLE
Select-MGProfile Beta is not recognizable

### ISSUE THREAD

**Issue by skydannypoint** [ruudmens/LazyAdmin#23]
The Get-MgMFAStatus script always produces this error when run;

Select-MgProfile: C:\Program Files\PowerShell\Scripts\Get-MgMFAStatus.ps1:69
Line |
  69 |    Select-MgProfile Beta
     |    ~~~~~~~~~~~~~~~~
     | The term 'Select-MgProfile' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
     | again.

Apparently this cmdlet is no longer usable since a newer version of the Graph powershell module was released.

**Comment by ruudmens** [comment]
Fixed in the last commit. Select-MgProfile is indeed not supported anymore.
