### ISSUE TITLE
Could not load type 'System.Security.Cryptography.SHA256Cng'

### ISSUE THREAD

**Issue by TBSJordanNash** [ruudmens/LazyAdmin#5]
When running in PowerShell 7, the MSOnline module must be loaded using compatibility mode (-UseWindowsPowerShell) or it will fail:

Line |
 126 |        Connect-MsolService
     |        ~~~~~~~~~~~~~~~~~~~
     | Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral,
     | PublicKeyToken=b77a5c561934e089'.

**Comment by TBSJordanNash** [comment]
$psversiontable


Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by ruudmens** [comment]
I have updated the scripts with the following check:

`if ($Host.Version.Major -eq 7) {
      Import-Module MSOnline -UseWindowsPowershell
    }
    Connect-MsolService`
