### ISSUE TITLE
Not all users are being gathered

### ISSUE THREAD

**Issue by Cyclone47** [ruudmens/LazyAdmin#7]
When using this script (tested in 3 different tenants with global admin) some users are not being exported properly.
![image](https://user-images.githubusercontent.com/15861318/171996557-fb245b6a-d589-4c30-9077-93a2f01c1199.png)

Any clue how to resolve this? I tried troubleshooting it a lot but can't seem to find why it's doing this.

Get-EXOMailbox -Identity $identity -Properties GrantSendOnBehalfTo, ForwardingSMTPAddress | 
      select UserPrincipalName, DisplayName, PrimarySMTPAddress, RecipientType, RecipientTypeDetails, GrantSendOnBehalfTo, ForwardingSMTPAddress
      
      This seems to be going well; however the function Get-AllMailboxPermissions shows many empty lines
![image](https://user-images.githubusercontent.com/15861318/171996588-9c86e2f0-5721-4b09-b600-00f3d06dc2c9.png)

**Comment by Cyclone47** [comment]
I feel like it might have something to do with the inbox name as these tenants are Swedish.

**Comment by Ruud-Mens** [comment]
Can you check the calendar folder name with:
`Get-mailbox -Identity <YOUR-EMAIL-ADDRESS> | Get-MailboxFolderStatistics -FolderScope calendar | sort-object Name |ft Identity,Name`

**Comment by Ruud-Mens** [comment]
If you change [line 114](https://github.com/ruudmens/LazyAdmin/blob/74292e940778923bc7faaa5fcbef06a854a2ee75/Office365/MailboxPermissionReport.ps1#L114) to Kalender it should work.

**Comment by Cyclone47** [comment]
> 

Any way we can make this multi-language compatible? As an example; we have agenda, calendier, kalender, calendar. Or a variable to change?

**Comment by Cyclone47** [comment]
> If you change [line 114](https://github.com/ruudmens/LazyAdmin/blob/74292e940778923bc7faaa5fcbef06a854a2ee75/Office365/MailboxPermissionReport.ps1#L114) to Kalender it should work.

Thanks, I'll try!
